# Site settings
title: Initiatives à Boulogne sur mer
email: contact@encommuns.org
description: > # this means to ignore newlines until "baseurl:"
 Initiative sociales inspirantes sur Boulogne sur mer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://initiativeboulogne.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
logo: 
# Build settings
markdown: kramdown
